# Generated by Django 4.0.3 on 2022-03-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='标题')),
                ('url', models.URLField(verbose_name='文章URL')),
                ('content', models.CharField(blank=True, max_length=10000, verbose_name='内容')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('type', models.CharField(choices=[('ann', '通知'), ('new_p', '新增加病例')], max_length=10, verbose_name='类型')),
                ('pub_date', models.DateField(verbose_name='文章日期')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='修改日期')),
            ],
            options={
                'ordering': ('-edit_date',),
            },
        ),
    ]
