# Generated by Django 4.0.3 on 2022-03-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, max_length=10000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
    ]
