# Generated by Django 4.0.3 on 2022-04-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0002_alter_article_add_date_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(db_index=True, unique=True, verbose_name='文章URL'),
        ),
    ]
