# Generated by Django 4.0.3 on 2022-04-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0003_alter_article_source_alter_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('ann', '通知'), ('new_p', '新增加病例'), ('alert', '检测结果异常')], max_length=10, verbose_name='类型'),
        ),
    ]
