# Generated by Django 4.0.3 on 2022-04-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0004_alter_article_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-pub_date',)},
        ),
    ]
