# Generated by Django 4.0.3 on 2022-04-03 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0006_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='article_relatived',
            new_name='article_related',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='add_now',
        ),
        migrations.AddField(
            model_name='patient',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='address_now',
            field=models.CharField(blank=True, max_length=30, verbose_name='现在住址'),
        ),
        migrations.AddField(
            model_name='patient',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
